# PyTorch Fundamentals

### Importing the libraries

In [34]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cu128


## Introduction to Tensors

### **Creating tensors**
PyTorch tensors are crated using `torch.Tensor()` = https://docs.pytorch.org/docs/stable/tensors.html

#### **Scalar**

In [35]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [36]:
scalar.ndim

0

In [37]:
# Get tensors as back as python int
scalar.item()

7

#### **Vector**

In [38]:
vector = torch.Tensor([7, 7])
vector

tensor([7., 7.])

In [39]:
vector.ndim

1

In [40]:
vector.shape

torch.Size([2])

#### **MATRIX**

In [41]:
MATRIX = torch.Tensor([[7, 8], [9, 8]])
MATRIX

tensor([[7., 8.],
        [9., 8.]])

In [42]:
MATRIX.ndim

2

In [43]:
MATRIX[1]

tensor([9., 8.])

In [44]:
MATRIX.shape

torch.Size([2, 2])

#### **TENSOR**

In [46]:
scalar.ndim

0

In [47]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [48]:
TENSOR.ndim

3

In [49]:
TENSOR.shape

torch.Size([1, 3, 3])

In [50]:
TENSOR[0][0]

tensor([1, 2, 3])

### Random tensors
why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random nubmers to better represent  the data.

`Start with random numbers -> Look at data -> Update random numbers -> look at data -> update random numbers`

Torch random tensors - https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [51]:
# Create a random number tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7144, 0.4981, 0.7991, 0.1634],
        [0.7467, 0.8955, 0.9993, 0.3190],
        [0.2363, 0.7266, 0.2071, 0.2460]])

In [52]:
random_tensor.ndim

2

In [54]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [56]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [59]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [61]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [72]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note:** Tensor datatype is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# Float 32 tensor
float_32__tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None, # What datatype is tensor (eg: float32 or float16)
                                device=None,
                                requires_grad=False)

float_32__tensor

tensor([3., 6., 9.])

In [78]:
float_32__tensor.dtype

torch.float16